import OpenAI from "openai";
import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

type Language = "en" | "de";

function cleanJsonText(text: string) {
  return text
    .trim()
    .replace(/^```json\s*/i, "")
    .replace(/^```\s*/i, "")
    .replace(/```$/i, "")
    .trim();
}

function getLanguageInstruction(language: Language) {
  return language === "de"
    ? "Respond ONLY in German language using professional, native-level fluency. Keep the requested structure exactly the same."
    : "Respond ONLY in English language. Keep the requested structure exactly the same.";
}

export async function POST(req: Request) {
  try {
    const apiKey = process.env.OPENAI_API_KEY;

    if (!apiKey) {
      console.error("OPENAI_API_KEY is missing in Vercel environment.");
      return NextResponse.json(
        {
          success: false,
          message: "Server configuration error.",
        },
        { status: 500 }
      );
    }

    const body = await req.json();
    const industry = String(body?.industry ?? "").trim();
    const description = String(body?.description ?? "").trim();
    const mode = String(body?.mode ?? "generate").trim();
    const language: Language = body?.language === "en" ? "en" : "de";

    if (!industry || !description) {
      return NextResponse.json(
        {
          success: false,
          message: "Industry and Description are required.",
        },
        { status: 400 }
      );
    }

    const openai = new OpenAI({ apiKey });
    const langInstruction = getLanguageInstruction(language);

    let prompt = "";
    let temperature = 0.7;
    let max_tokens = 1000;

    switch (mode) {
      case "title": {
        temperature = 0.4;
        max_tokens = 30;

        prompt = `
You are a concise labeling assistant.

${langInstruction}

Generate a SHORT, descriptive conversation title for the following user context.

RULES:
- Maximum 5 words
- No punctuation at the end
- No quotes around the title
- Capture the essence of the profession/industry
- Return ONLY the title, nothing else

Industry: ${industry}
Description: ${description}

Title:
`;
        break;
      }

      case "compare": {
        temperature = 0.35;
        max_tokens = 2200;

        prompt = `
You are an expert workforce analyst and software/tooling intelligence engine.

${langInstruction}

User Context:
Industry: ${industry}
Description: ${description}

Your task:
Generate a realistic weekly workload breakdown for this role AND generate the most relevant selectable tool chips for each activity.

CRITICAL TOOL RULES:
- Tool chips must be generated by your own intelligence from the exact activity, role, industry, and description.
- Do NOT use a fixed generic list. Do NOT dump the same tools under every activity.
- Each activity must have 8 to 20 toolOptions. Prefer 10 to 14 when possible.
- Every tool must be directly useful for that exact activity.
- Avoid unrelated cross-industry tools.
- Do not suggest developer tools for admissions, healthcare, e-commerce operations, marketing strategy, client communication or design coordination unless the role clearly involves software development.
- Prefer current, recognizable, practical tools used by professionals.
- Do not include vague categories when a named platform is more appropriate.

ACTIVITY RULES:
- Total working time MUST be approximately 40 hours/week.
- Show 5 to 8 meaningful activity categories.
- Each activity must have an hours range such as 6-8 hrs/week.
- Activity names must be specific and practical.
- Activities must reflect real behavior for the role, not generic office work.

Return ONLY valid JSON.
No markdown.
No explanations outside JSON.

Return JSON exactly in this structure:

{
  "activities": [
    {
      "title": "Specific activity name",
      "hours": "6-8 hrs/week",
      "toolOptions": ["8 to 20 highly relevant activity-specific tools"]
    }
  ]
}
`;
        break;
      }

      case "activity-analysis": {
        temperature = 0.45;
        max_tokens = 2600;

        const activitiesJson = JSON.stringify(body?.activities ?? []);

        prompt = `
You are a senior AI productivity and workflow optimization analyst.

${langInstruction}

User Context:
Industry: ${industry}
Job Description: ${description}

Activity Context Provided By User:
${activitiesJson}

Your task:
Analyze the weekly activity breakdown using the activity name, weekly hours, the user's own explanation, and selected tools.

For each activity:
1. Explain what the person is actually spending time on.
2. Detect workflow maturity from the selected tools.
3. Identify manual work, weak tooling, repeated effort, debugging friction, communication overhead, documentation gaps, or automation gaps.
4. Recommend practical tools, technologies, software, methods, or workflow improvements that match the exact activity and industry.
5. Estimate realistic weekly time saving.

STRICT WRITING RULES:
- Speak DIRECTLY to the user using "you" and "your".
- NEVER write "the user", "this user", "they", or indirect third-person phrasing.
- Do not give generic productivity advice.
- Every sentence must connect to the activity description, selected tools, or weekly hours.
- The analysis field must be 4-6 complete sentences and around 80-120 words for each activity.
- Recommend tools only when they fit the exact activity.
- The recommendedTools array should contain 3-5 high-impact tools, technologies, software platforms or methods.
- Time saving must be realistic, such as "1-2 hrs/week" or "4-6 hrs/week".
- Return ONLY valid JSON.
- No markdown.
- No extra commentary outside JSON.

Return JSON exactly in this structure:

{
  "overview": "A direct 2-3 sentence overall workflow diagnosis written to the user using you/your.",
  "activities": [
    {
      "title": "Activity title exactly as provided",
      "analysis": "Direct, polished 4-6 sentence recommendation addressed to the user.",
      "recommendedTools": ["Relevant tool 1", "Relevant tool 2", "Relevant tool 3"],
      "automationGaps": ["Gap 1", "Gap 2"],
      "timeSaving": "X-Y hrs/week"
    }
  ]
}
`;
        break;
      }

      default: {
        temperature = 0.7;
        max_tokens = 1200;

        prompt = `
You are an expert labor market analyst specializing in workforce classification and job role analysis in Germany.

${langInstruction}

User Input:
Industry: ${industry}
Description: ${description}

Your task:
1. Map the user's input to a REAL and OFFICIAL industry category.
2. Identify the TRUE professional work field.
3. Provide a strong, structured explanation.
4. Provide a realistic benchmark in Germany.

STRICT RULES:
- MUST use complete, professional sentences.
- MUST clearly describe responsibilities and nature of work.
- MUST include 1-2 bold insights using **double asterisks**.
- MUST NOT repeat the user input directly.
- MUST NOT hallucinate unrealistic numbers.
- If exact data is unknown, provide a logical approximation range.

FORMAT YOUR RESPONSE EXACTLY LIKE THIS:

**Industry**
<Official industry name>

**Work Field**
<Professional classification>

**Description**
Write 4-7 full sentences explaining the role clearly.
Include:
- What the person actually does
- Key responsibilities
- Tools/skills involved
- 1-2 important insights in **bold**

**Benchmark**
<Approximate number or range of similar professionals in Germany>

**Next**
Would you like to see what activities they spend their working week doing?
`;
        break;
      }
    }

    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "user",
          content: prompt,
        },
      ],
      temperature,
      max_tokens,
    });

    const aiText = cleanJsonText(completion.choices[0]?.message?.content || "");

    if (!aiText) {
      return NextResponse.json(
        {
          success: false,
          message: "AI returned an empty response.",
        },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      data: {
        message: aiText,
      },
    });
  } catch (error: any) {
    console.error("Productivity API error:", error);

    return NextResponse.json(
      {
        success: false,
        message: "Internal server error.",
      },
      { status: 500 }
    );
  }
}